- name: "CURRICULUM 1: NO PIPES, 2 moves per second"
  num_episodes: 1000
  action_tick: 30
  target_frames: 1200
  initial_exploration_rate: 0.7
  exploration_rate_decay: 0.9896  # Min @ 500 episodes
  is_pipes_active: false
  pipe_gap_size_mode: "random"
  pipe_distance_mode: "random"
  pipe_gap_loc_mode: "random"

- name: "CURRICULUM 2: NO PIPES, 3 moves per second"
  num_episodes: 1000
  action_tick: 20
  target_frames: 1200
  initial_exploration_rate: 0.6
  exploration_rate_decay: 0.9851  # Min @ 200 episodes
  is_pipes_active: false
  pipe_gap_size_mode: "random"
  pipe_distance_mode: "random"
  pipe_gap_loc_mode: "random"

- name: "CURRICULUM 3: NO PIPES, 4 moves per second"
  num_episodes: 1000
  action_tick: 15
  target_frames: 1200
  initial_exploration_rate: 0.5
  exploration_rate_decay: 0.9723  # Min @ 100 episodes
  is_pipes_active: false
  pipe_gap_size_mode: "random"
  pipe_distance_mode: "random"
  pipe_gap_loc_mode: "random"

- name: "CURRICULUM 4: LARGE CENTERED GAPS WITH PIPES FAR APART"
  num_episodes: 1000
  action_tick: 15
  target_frames: 1200
  initial_exploration_rate: 0.5
  exploration_rate_decay: 0.9723  # Min @ 100 episodes
  is_pipes_active: false
  pipe_gap_size_mode: "large"
  pipe_distance_mode: "large"
  pipe_gap_loc_mode: "center"

- name: "CURRICULUM 5: CENTERED GAPS WITH PIPES FAR APART"
  num_episodes: 1000
  action_tick: 15
  target_frames: 1200
  initial_exploration_rate: 0.5
  exploration_rate_decay: 0.9723  # Min @ 100 episodes
  is_pipes_active: false
  pipe_gap_size_mode: "random"
  pipe_distance_mode: "large"
  pipe_gap_loc_mode: "center"

- name: "CURRICULUM 6: SMALL CENTERED GAPS WITH PIPES FAR APART"
  num_episodes: 1000
  action_tick: 15
  target_frames: 1200
  initial_exploration_rate: 0.5
  exploration_rate_decay: 0.9723  # Min @ 100 episodes
  is_pipes_active: false
  pipe_gap_size_mode: "small"
  pipe_distance_mode: "large"
  pipe_gap_loc_mode: "center"

- name: "CURRICULUM 7: LARGE TOP GAPS WITH PIPES FAR APART"
  num_episodes: 1000
  action_tick: 15
  target_frames: 1200
  initial_exploration_rate: 0.5
  exploration_rate_decay: 0.9723  # Min @ 100 episodes
  is_pipes_active: false
  pipe_gap_size_mode: "large"
  pipe_distance_mode: "large"
  pipe_gap_loc_mode: "top"

- name: "CURRICULUM 8: TOP GAPS WITH PIPES FAR APART"
  num_episodes: 1000
  action_tick: 15
  target_frames: 1200
  initial_exploration_rate: 0.5
  exploration_rate_decay: 0.9723  # Min @ 100 episodes
  is_pipes_active: false
  pipe_gap_size_mode: "random"
  pipe_distance_mode: "large"
  pipe_gap_loc_mode: "top"

- name: "CURRICULUM 9: SMALL TOP GAPS WITH PIPES FAR APART"
  num_episodes: 1000
  action_tick: 15
  target_frames: 1200
  initial_exploration_rate: 0.5
  exploration_rate_decay: 0.9723  # Min @ 100 episodes
  is_pipes_active: false
  pipe_gap_size_mode: "small"
  pipe_distance_mode: "large"
  pipe_gap_loc_mode: "top"

- name: "CURRICULUM 10: LARGE BOTTOM GAPS WITH PIPES FAR APART"
  num_episodes: 1000
  action_tick: 15
  target_frames: 1200
  initial_exploration_rate: 0.5
  exploration_rate_decay: 0.9723  # Min @ 100 episodes
  is_pipes_active: false
  pipe_gap_size_mode: "large"
  pipe_distance_mode: "large"
  pipe_gap_loc_mode: "bottom"

- name: "CURRICULUM 11: BOTTOM GAPS WITH PIPES FAR APART"
  num_episodes: 1000
  action_tick: 15
  target_frames: 1200
  initial_exploration_rate: 0.5
  exploration_rate_decay: 0.9723  # Min @ 100 episodes
  is_pipes_active: false
  pipe_gap_size_mode: "random"
  pipe_distance_mode: "large"
  pipe_gap_loc_mode: "bottom"

- name: "CURRICULUM 12: SMALL BOTTOM GAPS WITH PIPES FAR APART"
  num_episodes: 1000
  action_tick: 15
  target_frames: 1200
  initial_exploration_rate: 0.5
  exploration_rate_decay: 0.9723  # Min @ 100 episodes
  is_pipes_active: false
  pipe_gap_size_mode: "small"
  pipe_distance_mode: "large"
  pipe_gap_loc_mode: "bottom"

- name: "CURRICULUM 13: ALTERNATING LARGE GAPS WITH PIPES FAR APART"
  num_episodes: 1000
  action_tick: 15
  target_frames: 1200
  initial_exploration_rate: 0.5
  exploration_rate_decay: 0.9723  # Min @ 100 episodes
  is_pipes_active: true
  pipe_gap_size_mode: "large"
  pipe_distance_mode: "large"
  pipe_gap_loc_mode: "alternating"

- name: "CURRICULUM 14: ALTERNATING GAPS WITH PIPES FAR APART"
  num_episodes: 1000
  action_tick: 15
  target_frames: 1200
  initial_exploration_rate: 0.5
  exploration_rate_decay: 0.9723  # Min @ 100 episodes
  is_pipes_active: true
  pipe_gap_size_mode: "random"
  pipe_distance_mode: "large"
  pipe_gap_loc_mode: "alternating"

- name: "CURRICULUM 15: ALTERNATING SMALL GAPS WITH PIPES FAR APART"
  num_episodes: 1000
  action_tick: 15
  target_frames: 1200
  initial_exploration_rate: 0.5
  exploration_rate_decay: 0.9723  # Min @ 100 episodes
  is_pipes_active: true
  pipe_gap_size_mode: "small"
  pipe_distance_mode: "large"
  pipe_gap_loc_mode: "alternating"

- name: "CURRICULUM 16: RANDOM SMALL GAPS WITH PIPES FAR APART"
  num_episodes: 1000
  action_tick: 15
  target_frames: 1200
  initial_exploration_rate: 0.5
  exploration_rate_decay: 0.9723  # Min @ 100 episodes
  is_pipes_active: true
  pipe_gap_size_mode: "small"
  pipe_distance_mode: "large"
  pipe_gap_loc_mode: "random"

- name: "CURRICULUM 17: FULL GAME"
  num_episodes: 1000
  action_tick: 15
  target_frames: 3600
  initial_exploration_rate: 0.4
  exploration_rate_decay: 0.9871  # Min @ 200 episodes
  is_pipes_active: true
  pipe_gap_size_mode: "random"
  pipe_distance_mode: "random"
  pipe_gap_loc_mode: "random"
